// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MQTT_Dashboard

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton8 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_right_png, NULL);
    lv_obj_set_height(ui_ImgButton8, 64);
    lv_obj_set_width(ui_ImgButton8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton8, 360);
    lv_obj_set_y(ui_ImgButton8, 200);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    ui_ImgButton9 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_left_png, NULL);
    lv_obj_set_height(ui_ImgButton9, 64);
    lv_obj_set_width(ui_ImgButton9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton9, -360);
    lv_obj_set_y(ui_ImgButton9, 200);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    ui_Image7 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image7, &ui_img_do_subscribe_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image7, -231);
    lv_obj_set_y(ui_Image7, -27);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image8, &ui_img_qr_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 375
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 375
    lv_obj_set_x(ui_Image8, 148);
    lv_obj_set_y(ui_Image8, -27);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);

}
